/*
 * PanelBuscarMaquina.java
 *
 * Created on 26 de octubre de 2008, 18:54
 */

package sgvet.igu.buscar;

import sgvet.igu.*;
import java.util.List;
import javax.persistence.Query;
import sgvet.persistencia.FachadaPersistencia;
import javax.swing.*;
import sgvet.entidades.OrdenCompra;
import sgvet.igu.model.BuscarOrdenCompraTableModel;

/**
 *
 * @author  stafoxter
 */
public class PanelBuscarOrdenCompra extends javax.swing.JDialog {
    private static final long serialVersionUID = 1L;


    private List<OrdenCompra> ordenesCompra;
    private BuscarOrdenCompraTableModel tm;
    private PanelOrdenCompra panelOrdenCompra;
    //private OrdenCompra ordenCompra;
    
    /** Creates new form PanelBuscarMaquina */
    public PanelBuscarOrdenCompra(PanelOrdenCompra panel) {
        initComponents();
        panelOrdenCompra=panel;
        inicializar();
    }
    
    
    private void inicializar() {
        tm = new BuscarOrdenCompraTableModel(0);
        tOrdenCompra.setModel(tm);
        tOrdenCompra.setSelectionMode(ListSelectionModel.SINGLE_SELECTION );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pBuscar = new javax.swing.JPanel();
        lbNombre = new javax.swing.JLabel();
        tfNroOrden = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        pBoton = new javax.swing.JPanel();
        btAceptar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tOrdenCompra = new org.jdesktop.swingx.JXTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Orden Compra");

        lbNombre.setText("Nro Orden:");

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pBuscarLayout = new javax.swing.GroupLayout(pBuscar);
        pBuscar.setLayout(pBuscarLayout);
        pBuscarLayout.setHorizontalGroup(
            pBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNroOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pBuscarLayout.setVerticalGroup(
            pBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBuscarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(tfNroOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar))
                .addGap(31, 31, 31))
        );

        btAceptar.setText("Aceptar");
        btAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });
        pBoton.add(btAceptar);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        pBoton.add(btCancelar);

        tOrdenCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nro Orden", "Proveedor", "Fecha Emisión", "Fecha Entrega", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tOrdenCompra.setEditable(false);
        jScrollPane1.setViewportView(tOrdenCompra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                    .addComponent(pBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addGap(125, 125, 125)
                .addComponent(pBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
    dispose();
}//GEN-LAST:event_btCancelarActionPerformed

private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
    tm.limpiarTableModel();
    
    Query consulta; 
    
    if(tfNroOrden.getText().trim().equals("")){
        consulta = FachadaPersistencia.getInstancia().crearConsulta("Select a from OrdenCompra a where a.borrado=false");
    }else{
        consulta= FachadaPersistencia.getInstancia().crearConsulta("Select a from OrdenCompra a where (a.nroOrdenCompra) LIKE :nro and a.borrado=false" );
        consulta.setParameter("nro", tfNroOrden.getText());
    }
    
    
     
    ordenesCompra = FachadaPersistencia.getInstancia().buscar(OrdenCompra.class, consulta);

    
    for (int i = 0; i < ordenesCompra.size(); i++) {
        tm.agregarFila(ordenesCompra.get(i));
    }
    
}//GEN-LAST:event_btBuscarActionPerformed

private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
    int indice = tOrdenCompra.convertRowIndexToModel(tOrdenCompra.getSelectedRow());
    OrdenCompra resultado;
 
    if(indice ==-1 ){
        JOptionPane.showMessageDialog(this, "No se ha seleccionado Orden Compra");
    }else{
        resultado = tm.getFila(indice);
//        if(tipoBusqueda == 1){
//            if(tm.getRowCount()<1){
//                tm.agregarFila(resultado);       
//                dispose();
//            }
//            else{
//                if(ValidacionBuscar.getInstancia().maquinaEstaCargadaEnTabla(tm, resultado)){
//                    JOptionPane.showMessageDialog(this, "La maquina ya se encuentra cargada");
//                }
//                else{
//                    tm.agregarFila(resultado);       
//                    dispose();
//                }
//            }
//        }else{
            panelOrdenCompra.setOrdenCompra(resultado);
            dispose();
//        }
    }
}//GEN-LAST:event_btAceptarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAceptar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JPanel pBoton;
    private javax.swing.JPanel pBuscar;
    private org.jdesktop.swingx.JXTable tOrdenCompra;
    private javax.swing.JTextField tfNroOrden;
    // End of variables declaration//GEN-END:variables

}
